'use client'

import React from 'react'
import { motion } from 'framer-motion'
import Link from 'next/link'

const NotFound = () => {
  return (
    <div className="flex flex-col min-h-[70vh] w-full justify-center items-center gap-10">
      {/* Animated icon */}
      <motion.div
        initial={{ scale: 0.8, opacity: 0 }}
        animate={{ scale: 1, opacity: 1 }}
        transition={{ duration: 0.4, ease: 'easeOut' }}
        className="flex items-center justify-center w-24 h-24 rounded-full bg-primary/20 text-primary shadow-inner"
      >
        <span className="text-4xl font-bold">?</span>
      </motion.div>

      {/* Text section */}
      <motion.div
        initial={{ y: 20, opacity: 0 }}
        animate={{ y: 0, opacity: 1 }}
        transition={{ delay: 0.15, duration: 0.5 }}
        className="flex flex-col items-center justify-center text-center max-w-md"
      >
        <h1 className="text-3xl font-semibold text-primary">Page not found</h1>
        <p className="mt-2 text-base text-muted-foreground">
          We couldn’t find the page you’re looking for. Here’s a random image
          generated by{' '}
          <span className="font-medium text-vivid">Creative AI</span>.
        </p>
      </motion.div>

      {/* Button */}
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ delay: 0.3 }}
      >
        <Link
          href="/"
          className="inline-flex items-center justify-center rounded-md bg-primary px-5 py-2.5 text-sm font-medium text-primary-foreground shadow-sm transition-all hover:shadow-md focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary/50"
        >
          Go back home
        </Link>
      </motion.div>
    </div>
  )
}

export default NotFound
